name: Sync With Master And Build

on:
  schedule:
    - cron: '* * * * *'


jobs:
  sync-with-master-and-build:
    runs-on: 'ubuntu:20.04'
    steps:
      - name: Update system
        run: sudo apt-get update && sudo apt-get dist-upgrade -y
        
      - name: Install latest gcc
        run: sudo apt-get install gcc-10
      
      - name: Get dependencies
        run: sudo apt-get build-dep vlc
      
      - name: Get latest vlc sources
        run: wget -r --no-parent -A 'vlc-*.tar.xz' -R "index.html*" -O vlc.tar.xz http://download.videolan.org/pub/videolan/vlc/last/
        
      - name: Upload Built Packages
        uses: actions/upload-artifact@v2
        with:
          name: vlc-build
          path: ./*.tar.xz
            
      - run: ./.github/scripts/build.sh
        shell: bash
